### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by Lemar98** [bundabrg/bcf#14]
Is it possible to pass some objects to the class with the logic of the command using the constructor?

**Comment by bundabrg** [comment]
I'm hitting this same issue so I'm investigating if there's any reason why we can't pass an instantiated Command class instead of passing it as a class object. This will mean it can have its own constructor for this purpose.

**Comment by Lemar98** [comment]
Is there any deadline for resolving the issue? I have a burning question about using the commands api right now, but I can't use your api without dependency injection. If this is implemented in the near future then I will use your api otherwise I will have to look for something else

**Comment by bundabrg** [comment]
I'm working on it at the moment so hopefully soon since its a bit of an overhaul of everything, possibly even later today.
If looking at other command frameworks its worth looking at [ACF](https://github.com/aikar/commands) as this is inspired by it and has a tonne more work under it.

**Comment by Lemar98** [comment]
thanks
